Вход на сайт
htmlacademy-php1/889991-yeticave-13 pull request #15
Opened 2021-09-02 11:05 UTC by YaroslavSavele

2021-09-03 11:40 UTC, ademaro commented on .vscode/launch.json
> +{
этот файл надо убрать из репозитория

2021-09-03 11:41 UTC, ademaro commented on add.php
> +    print($layout_content);
после этого нам надо прекращать тогда сценарий, а он пока продолжает выполняться

2021-09-03 11:42 UTC, ademaro commented on lot.php
> +//$page_404 = include_template("404.php", [
комменты удаляем из когда

2021-09-03 11:43 UTC, ademaro commented on models.php
> +    $res = mysqli_stmt_execute($stmt);
у нас же уже есть готовая функция, зачем дублировать? Просто вызвать её можем тут

2021-09-03 11:43 UTC, ademaro commented on schema.sql
> +DROP DATABASE IF EXISTS yeticave;
👍🏼

2021-09-03 11:44 UTC, ademaro commented on templates/main-403.php
> +    </nav>
эту часть предлагаю вынести в отдельный подшаблон

2021-09-03 11:44 UTC, ademaro requested changes
Жду поправок, в целом всё ок)

2021-09-06 11:50 UTC, ademaro commented on add.php
> +        "header" => $header
HTTP-заголовок я имел в виду) 403 должна отдавать эта страница (HTTP статус-код)

2021-09-06 11:51 UTC, ademaro commented on templates/header.php
> +
Тут — отлично!

2021-09-06 11:51 UTC, ademaro commented on templates/main-403.php
> +    <?= $header; ?>
👍🏼  в других шаблонах — так же вынести надо

2021-09-06 11:52 UTC, ademaro approved these changes
Так, отлично, ПР закрываю, летим дальше!

2021-09-06 11:52 UTC, merged

2021-09-06 17:36 UTC, YaroslavSavele commented on add.php
> +        "header" => $header
Но так же лучше? Мы же 404 так сделали, красота же?

2021-09-06 17:36 UTC, YaroslavSavele commented on templates/main-403.php
> +    <?= $header; ?>
Хорошо, сделаю