Добавляет категории и товары
htmlacademy-php1/889991-yeticave-13 pull request #3
Opened 2021-07-24 05:20 UTC by YaroslavSavele

2021-07-24 10:35 UTC, ademaro commented on index.php
> +        $categories = ["Доски и лыжи", "Крепления", "Ботинки", "Одежда", "Инструменты", "Разное"];
давай определимся с единообразием кавычек — либо двойные для php (с ними можно интерполировать переменные внутри строк), либо — одинарные

2021-07-24 10:36 UTC, ademaro commented on index.php
> +        $categories = ["Доски и лыжи", "Крепления", "Ботинки", "Одежда", "Инструменты", "Разное"];
По поводу этого массива — давай сделаем ассоциативным, тк нам потребуется как минимум ключи для модификаторов класса в разметке для категорий

2021-07-24 10:37 UTC, ademaro commented on index.php
> +              'category' => 'Доски и лыжи',
Давай подумаем как связать структуру товаров с категориями

2021-07-24 10:37 UTC, ademaro commented on index.php
> +            <?php foreach ($categories as $val): ?>
вместо val давай осознанные названия придумывать, тут подошло бы category или category_name, например

2021-07-24 10:38 UTC, ademaro commented on index.php
> +            <?php foreach ($goods as $val): ?>
val -> good (product)?

2021-07-24 10:40 UTC, ademaro commented on index.php
>              <li class="promo__item promo__item--boards">
boards — модификатор для категории, обрати внимание. В шаблоне есть доступные варианты, можешь сразу посмотреть и сохранить названия в массиве categories

2021-07-24 10:40 UTC, ademaro requested changes
В целом всё супер, молодец! Давай немного доработаем и двинем дальше

2021-07-24 10:40 UTC, ademaro commented
ПР пока оставляю открытым, жду правок

2021-07-24 16:30 UTC, YaroslavSavele commented on index.php
> +        $categories = ["Доски и лыжи", "Крепления", "Ботинки", "Одежда", "Инструменты", "Разное"];
Да, точно, а я хотел функцию писать, что бы модификатор класса подставлялся какой надо, а это гораздо проще и красивей получится. Спасибо.

2021-07-24 16:44 UTC, YaroslavSavele commented
ок

2021-07-26 18:49 UTC, ademaro commented on index.php
> +            <li class="promo__item promo__item--<?=$key;?>">
чаще добавляют пробелы для лучшей читаемости: `<?= $key; ?>`

2021-07-26 18:49 UTC, ademaro commented on index.php
> +            <?php foreach ($categories as $val): ?>
$val надо переименовать

2021-07-26 18:50 UTC, ademaro commented on index.php
> +            <?php foreach ($goods as $key => $good): ?>
зачем тут нам вообще $key? `<?php foreach ($goods as $good): ?>`

2021-07-26 18:50 UTC, ademaro approved these changes
Отлично, летим дальше, поправки жду в следующем задании отдельным коммитом

2021-07-26 18:50 UTC, merged